import argparse
import json
import os
import time
from pathlib import Path

from buddhi_ai.db.connection import init_db
from buddhi_ai.parser.tree_sitter import parse_file, LANGUAGE_MAP, load_languages
from buddhi_ai.parser.entropy import filter_boilerplate
from buddhi_ai.graph.builder import load_graph
from buddhi_ai.graph.clustering import run_leiden
from buddhi_ai.graph.sync import update_communities


# ---------------------------------------------------------------------------
# Plugin descriptor templates (written into the target workspace)
# ---------------------------------------------------------------------------

_PLUGIN_JSON: dict = {
    "name": "buddhi-ai",
    "version": "1.0.0",
    "description": "Graph-based token optimization and context management layer",
}

_MCP_CONFIG_JSON: dict = {
    "mcpServers": {
        "buddhi-ai-core": {
            "command": "buddhi-mcp",
            "args": [],
            "env": {
                "BUDDHI_DB_PATH": ".buddhi/graph.db",
            },
        }
    }
}

_HOOKS_JSON: dict = {
    "io-gating-rules": {
        "enabled": True,
        "PreToolUse": [
            {
                "matcher": "view_file|grep_search|find_by_name|read_file",
                "hooks": [
                    {
                        "command": "python -m buddhi_ai.hooks.gate_io",
                        "timeout": 5,
                    }
                ],
            }
        ],
    },
    "shell-proxy-rules": {
        "enabled": True,
        "PreToolUse": [
            {
                "matcher": "run_command",
                "hooks": [
                    {
                        "command": "python -m buddhi_ai.hooks.shell_proxy",
                        "timeout": 120,
                    }
                ],
            }
        ],
    },
    "trajectory-injection-rules": {
        "enabled": True,
        "PreInvocation": [
            {
                "command": "python -m buddhi_ai.hooks.pre_invoke",
                "timeout": 5,
            }
        ],
    },
}


def _scaffold_workspace_plugin(workspace_root: str) -> None:
    """Create .agents/plugins/buddhi-ai/ with the required descriptor files.

    This is idempotent — existing files are overwritten with the latest
    configuration so incremental ``buddhi init`` runs always refresh the
    plugin definition.
    """
    plugin_dir = Path(workspace_root) / ".agents" / "plugins" / "buddhi-ai"
    plugin_dir.mkdir(parents=True, exist_ok=True)

    # Ensure .agents gets its own .gitignore
    agents_dir = Path(workspace_root) / ".agents"
    gitignore = agents_dir / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(
            "# Generated by Buddhi AI — plugin workspace artifacts\n*\n",
            encoding="utf-8",
        )

    files: dict[str, dict] = {
        "plugin.json": _PLUGIN_JSON,
        "mcp_config.json": _MCP_CONFIG_JSON,
        "hooks.json": _HOOKS_JSON,
    }

    for filename, content in files.items():
        target = plugin_dir / filename
        target.write_text(
            json.dumps(content, indent=2) + "\n",
            encoding="utf-8",
        )

    print(f"  Plugin scaffolded at: {plugin_dir.relative_to(workspace_root)}")


def handle_init(args: argparse.Namespace) -> None:
    workspace_root = os.getcwd()
    print(f"Initializing buddhi-ai in workspace: {workspace_root}")
    print(f"Entropy threshold: {args.entropy_threshold}")

    # Initialize DB
    conn = init_db(workspace_root)
    load_languages()

    supported_exts = set(LANGUAGE_MAP.keys())

    scanned_count = 0
    skipped_count = 0
    filtered_nodes_count = 0
    inserted_nodes_count = 0

    # Simple sequential walk
    for root, dirs, files in os.walk(workspace_root):
        # Exclude common directories
        if ".git" in dirs:
            dirs.remove(".git")
        if ".buddhi" in dirs:
            dirs.remove(".buddhi")
        if ".venv" in dirs:
            dirs.remove(".venv")
        if "node_modules" in dirs:
            dirs.remove("node_modules")
        if ".agents" in dirs:
            dirs.remove(".agents")

        for file in files:
            filepath = Path(root) / file
            if filepath.suffix.lower() not in supported_exts:
                continue

            try:
                mtime = os.path.getmtime(filepath)
            except OSError:
                continue

            rel_path = str(filepath.relative_to(workspace_root))

            # Check incremental update
            cur = conn.cursor()
            cur.execute("SELECT id, mtime FROM files WHERE path = ?", (rel_path,))
            row = cur.fetchone()

            file_id = None
            if row:
                file_id, db_mtime = row
                if db_mtime == mtime:
                    # Unchanged
                    skipped_count += 1
                    continue

            # File is new or modified
            scanned_count += 1
            print(f"Scanning: {rel_path}")

            # Upsert file record
            current_time = time.time()
            if file_id:
                cur.execute(
                    "UPDATE files SET mtime = ?, last_scanned = ? WHERE id = ?",
                    (mtime, current_time, file_id),
                )
                # Delete old nodes to replace them (cascade should delete edges)
                cur.execute("DELETE FROM nodes WHERE file_id = ?", (file_id,))
            else:
                cur.execute(
                    "INSERT INTO files (path, mtime, last_scanned) VALUES (?, ?, ?)",
                    (rel_path, mtime, current_time),
                )
                file_id = cur.lastrowid

            # Parse file
            nodes = parse_file(filepath)
            language_name = LANGUAGE_MAP[filepath.suffix.lower()].name

            for node in nodes:
                content = node["content"]

                # Check entropy
                if filter_boilerplate(content, args.entropy_threshold):
                    filtered_nodes_count += 1
                    continue

                # Insert node
                # Note: tree-sitter node type mapping
                cur.execute(
                    """
                    INSERT INTO nodes (file_id, language, node_type, name, content, start_line, end_line, entropy_score)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        file_id,
                        language_name,
                        node["type"],
                        node["name"],
                        content,
                        node["start_line"],
                        node["end_line"],
                        0.0,  # Optional: store the actual score if needed
                    ),
                )
                inserted_nodes_count += 1

            conn.commit()

    print("\nScan Summary (Phase 1: Definitions):")
    print(f"  Files scanned: {scanned_count}")
    print(f"  Files skipped (unchanged): {skipped_count}")
    print(f"  Nodes inserted: {inserted_nodes_count}")
    print(f"  Boilerplate nodes filtered: {filtered_nodes_count}")
    
    print("\n--- Phase 1: Reference Mapping (Pass 2) ---")
    from buddhi_ai.parser.tree_sitter import extract_file_references
    edges_inserted = 0
    
    # 1. Clear old edges completely for simplicity (or let cascade handle it, but better safe)
    cur = conn.cursor()
    cur.execute("DELETE FROM edges")
    
    # 2. Build global symbol registry
    cur.execute("SELECT id, name, file_id FROM nodes")
    global_symbols: dict[str, list[tuple[int, int]]] = {}
    for node_id, name, file_id in cur.fetchall():
        if not name or name == "anonymous":
            continue
        if name not in global_symbols:
            global_symbols[name] = []
        global_symbols[name].append((node_id, file_id))

    # 3. Re-iterate files for references
    cur.execute("SELECT id, path FROM files")
    files_list = cur.fetchall()

    for file_id, rel_path in files_list:
        filepath = Path(workspace_root) / rel_path
        if not filepath.exists():
            continue
        
        refs = extract_file_references(filepath)
        identifiers = refs["identifiers"]
        imports = refs["imports"]
        
        # Get local nodes to act as edge sources
        cur.execute("SELECT id FROM nodes WHERE file_id = ?", (file_id,))
        local_nodes = [r[0] for r in cur.fetchall()]
        if not local_nodes:
            continue
            
        for ident in identifiers:
            if ident not in global_symbols:
                continue
            
            targets = global_symbols[ident]
            
            # 1. Local-First Matching
            local_targets = [t for t in targets if t[1] == file_id]
            if local_targets:
                for target_id, _ in local_targets:
                    for source_id in local_nodes:
                        if source_id != target_id:
                            cur.execute("INSERT INTO edges (source_id, target_id, relationship_type, weight) VALUES (?, ?, ?, ?)",
                                      (source_id, target_id, "colocated", 1.0))
                            edges_inserted += 1
                continue
                
            # 2. File-Import Intersection
            import_targets = []
            for target_id, t_file_id in targets:
                cur.execute("SELECT path FROM files WHERE id = ?", (t_file_id,))
                t_path = cur.fetchone()[0].replace("\\", "/").replace(".py", "").replace(".ts", "").replace(".js", "")
                t_path_parts = set(t_path.split("/"))
                
                # check intersection
                if any(imp in t_path_parts or imp in t_path.replace("/", ".") for imp in imports):
                    import_targets.append(target_id)
            
            if import_targets:
                weight = 1.0 / len(import_targets)
                for target_id in import_targets:
                    for source_id in local_nodes:
                        cur.execute("INSERT INTO edges (source_id, target_id, relationship_type, weight) VALUES (?, ?, ?, ?)",
                                  (source_id, target_id, "imported", weight))
                        edges_inserted += 1
                continue
                
            # 3. Multi-Target Penalty
            weight = 3.0 / len(targets)
            if weight < 0.1: # Skip generic ubiquitous names
                continue
                
            for target_id, _ in targets:
                for source_id in local_nodes:
                    cur.execute("INSERT INTO edges (source_id, target_id, relationship_type, weight) VALUES (?, ?, ?, ?)",
                              (source_id, target_id, "reference", weight))
                    edges_inserted += 1

    conn.commit()
    conn.close()
    print(f"  Edges inserted: {edges_inserted}")
    
    print("\n--- Phase 2: Topological Graph Clustering ---")
    db_path = os.path.join(workspace_root, ".buddhi", "graph.db")
    print("Loading graph into memory...")
    g, ig_id_to_db_id = load_graph(db_path)
    print(f"Graph loaded with {g.vcount()} nodes and {g.ecount()} edges.")
    
    if g.vcount() > 0:
        print("Running Leiden clustering algorithm...")
        community_mapping = run_leiden(g, ig_id_to_db_id)
        print(f"Identified {len(set(community_mapping.values()))} communities.")
        
        print("Synchronizing communities to database...")
        update_communities(db_path, community_mapping)
        print("Database synchronization complete.")
        
        print("\n--- Phase 3: Client Visualization ---")
        from buddhi_ai.graph.visualizer import generate_graph_html
        html_path = os.path.join(workspace_root, ".buddhi", "graph.html")
        print("Generating interactive graph visualization...")
        generate_graph_html(db_path, html_path)
    else:
        print("Graph is empty. Skipping clustering and visualization.")

    print("\n--- Phase 4: Workspace Plugin Scaffolding ---")
    _scaffold_workspace_plugin(workspace_root)

    print("\nDone.")
