import sqlite3
from pathlib import Path


def get_db_path(workspace_root: str) -> Path:
    """Returns the path to the localized SQLite graph database."""
    buddhi_dir = Path(workspace_root) / ".buddhi"
    buddhi_dir.mkdir(parents=True, exist_ok=True)
    
    gitignore_path = buddhi_dir / ".gitignore"
    if not gitignore_path.exists():
        gitignore_path.write_text("# Generated by Buddhi.\n*\n", encoding="utf-8")
        
    return buddhi_dir / "graph.db"


def init_db(workspace_root: str) -> sqlite3.Connection:
    """Initializes the database and runs the schema if needed."""
    db_path = get_db_path(workspace_root)
    conn = sqlite3.connect(db_path)

    # Check for legacy schema and wipe the db if necessary
    cursor = conn.cursor()
    cursor.execute("PRAGMA table_info(nodes)")
    columns = [col[1] for col in cursor.fetchall()]
    if columns and "file_id" not in columns:
        # Legacy schema detected, clear the database file completely
        conn.close()
        db_path.unlink()
        conn = sqlite3.connect(db_path)

    # Enforce foreign keys
    conn.execute("PRAGMA foreign_keys = ON;")

    # Run schema
    schema_path = Path(__file__).parent / "schema.sql"
    with open(schema_path, "r", encoding="utf-8") as f:
        schema_sql = f.read()

    conn.executescript(schema_sql)
    
    # Ensure community_id exists (for backwards compatibility with older db)
    try:
        conn.execute("ALTER TABLE nodes ADD COLUMN community_id INTEGER;")
    except sqlite3.OperationalError:
        pass
        
    conn.commit()

    return conn
