from typing import List, Optional, Union, Dict, Any, Literal
from pydantic import BaseModel, Field

class ChatMessage(BaseModel):
    role: str = Field(..., description="The role of the message author (system, user, assistant, or tool).")
    content: Optional[str] = Field(None, description="The contents of the message.")
    name: Optional[str] = Field(None, description="An optional name for the participant.")
    tool_call_id: Optional[str] = Field(None, description="Tool call that this message is responding to.")
    tool_calls: Optional[List[Dict[str, Any]]] = Field(None, description="The tool calls generated by the model.")

class ChatCompletionRequest(BaseModel):
    """
    Standard OpenAI Chat Completions API request payload.
    """
    model: str = Field("gemma-4-E4B-it.litertlm", description="The ID of the model to use.")
    messages: List[ChatMessage] = Field(..., description="A list of messages comprising the conversation so far.")
    stream: Optional[bool] = Field(False, description="If true, server-sent events will be streamed.")
    temperature: Optional[float] = Field(1.0, description="What sampling temperature to use.")
    max_tokens: Optional[int] = Field(None, description="The maximum number of tokens to generate.")
    tools: Optional[List[Dict[str, Any]]] = Field(None, description="A list of tools the model may call.")
    tool_choice: Optional[Union[str, Dict[str, Any]]] = Field(None, description="Controls which tool is called.")

class ChatCompletionResponseChoice(BaseModel):
    index: int = 0
    message: ChatMessage
    finish_reason: Optional[Literal["stop", "length", "tool_calls", "content_filter"]] = "stop"

class ChatCompletionUsage(BaseModel):
    prompt_tokens: int = 0
    completion_tokens: int = 0
    total_tokens: int = 0

class ChatCompletionResponse(BaseModel):
    """
    Standard OpenAI Chat Completions API response payload.
    """
    id: str = Field(..., description="A unique identifier for the chat completion.")
    object: Literal["chat.completion"] = "chat.completion"
    created: int = Field(..., description="The Unix timestamp (in seconds) of when the chat completion was created.")
    model: str = Field(..., description="The model used for the chat completion.")
    choices: List[ChatCompletionResponseChoice] = Field(..., description="A list of chat completion choices.")
    usage: Optional[ChatCompletionUsage] = Field(default_factory=ChatCompletionUsage, description="Usage statistics for the completion request.")
